

theme: tactile

# Name of your site (displayed in the header)
name: PPAT@MIT

# Short bio or description (displayed in the header)
description: PPAT Resources

footer-links:
  email: ppat@mit.edu
  github: PPAT-MIT

baseurl: ""


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

  exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME